### ISSUE TITLE
ImportError Libtorch_cpu.so: undefined symbol

### ISSUE THREAD

**Issue by EnnioEvo** [zhiqi-li/Panoptic-SegFormer#5]
Thank you for this awesome work

Unfortunately I can't run the training because I get the following error

```
./tools/dist_train.sh ./configs/panformer/panformer_r50_24e_coco_panoptic.py 1
+ CONFIG=./configs/panformer/panformer_r50_24e_coco_panoptic.py
+ GPUS=1
+ PORT=29503
++ dirname ./tools/dist_train.sh
++ dirname ./tools/dist_train.sh
+ PYTHONPATH=./tools/..:
+ python -m torch.distributed.launch --nproc_per_node=1 --master_port=29503 ./tools/train.py ./configs/panformer/panformer_r50_24e_coco_panoptic.py --launcher pytorch --deterministic
Traceback (most recent call last):
  File "/home/vision/anaconda3/envs/psf/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/vision/anaconda3/envs/psf/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/vision/anaconda3/envs/psf/lib/python3.7/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/vision/anaconda3/envs/psf/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl23shallow_copy_and_detachERKNS_15VariableVersionEb
```

This is my environment:

![screen](https://user-images.githubusercontent.com/26523410/163209193-db3de0c6-bfb3-494f-b9ec-6356cc1f7cff.png)
![screen1](https://user-images.githubusercontent.com/26523410/163209211-9eefefcf-cef5-435d-84a1-448640681097.png)

**Comment by Janet-H** [comment]
I have the same problem as yours, do you salve it ?
